pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:2.7.16-slim'
                            args '--user root'
                }
            }
            when {
                changeset '**/vote/**'
            }
            steps {
                echo 'Compiling vote app'
                dir ('vote') {
                    sh 'pip install -r requirements.txt'
                }
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'python:2.7.16-slim'
                            args '--user root'
                }
            }
            when {
                changeset '**/vote/**'
            }
            steps {
                echo 'Running unit tester on vote app'
                dir ('vote') {
                    sh 'pip install -r requirements.txt'
                    sh 'nosetests -v'
                }
            }
        }
        stage('docker-package') {
            agent any
            when {
                branch 'master'
                changeset '**/vote/**'
            }
            steps {
                echo 'Packaging the vote app'
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'fackohub') {
                        def voteImage = docker.build("airseneo/vote:v${env.BUILD_ID}", "./vote")
                        voteImage.push()
                        voteImage.push("${env.BRANCH_NAME}")
                    }
                }
            }
        }
    }
    post {
        always {
            echo 'Pipeline for vote app is complete...'
        }
        success {
            slackSend (channel: "devops-tools", message: "Build vote succeeded - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
        failure {
            slackSend (channel: "devops-tools", message: "Build vote failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
    }
}
