version: "3.9"

volumes:
  db-data:

networks:
  instavote:
    driver: bridge

services:
  vote:
    image: airseneo/vote:master
    build: ./vote
    ports:
      - 5001:80
    depends_on:
      - redis
    networks:
      - instavote

  redis:
    image: redis:alpine
    networks:
      - instavote

  db:
    image: postgres:9.4
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - "db-data:/var/lib/posgresql/data"
    networks:
      - instavote

  result:
    image: airseneo/result:master
    build: ./result
    ports:
      - 5002:4000
    depends_on:
      - db
    networks:
      - instavote

  worker:
    image: airseneo/worker:master
    build: ./worker
    depends_on:
      - db
      - redis
    networks:
      - instavote
