pipeline {
    agent any
    tools {
        maven 'maven 3.8.4'
    }
    stages {
        stage('Build') {
            steps {
                echo 'Compiling worker app'
                dir ('worker') {
                    sh 'mvn compile'
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Running unit tester on worker app'
                dir ('worker') {
                    sh 'mvn clean test'
                }
            }
        }
        stage('Package') {
            steps {
                echo 'Packaging the worker app'
                dir ('worker') {
                    sh 'mvn package'
                }
            }
        }
    }
    post {
        always {
            echo 'Pipeline for worker app is complete...'
        }
    }
}
