pipeline {
    agent any
    tools {
        maven 'maven 3.8.4'
    }
    stages {
        stage('Build') {
            when {
                changeset '**/worker/**'
            }
            steps {
                echo 'Compiling worker app'
                dir ('worker') {
                    sh 'mvn compile'
                }
            }
        }
        stage('Test') {
            when {
                changeset '**/worker/**'
            }
            steps {
                echo 'Running unit tester on worker app'
                dir ('worker') {
                    sh 'mvn clean test'
                }
            }
        }
        stage('Package') {
            when {
                branch 'master'
                changeset '**/worker/**'
            }
            steps {
                echo 'Packaging the worker app'
                dir ('worker') {
                    sh 'mvn package -DskipTests'
                    archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
                }
            }
        }
    }
    post {
        always {
            echo 'Pipeline for worker app is complete...'
        }
    }
    post {
        success {
            slackSend (channel: "devops-tools", message: "Build succeeded - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
            echo 'Pipeline for worker app is complete...'
        }
    }
    post {
        failure {
            slackSend (channel: "devops-tools", message: "Build failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
            echo 'Pipeline for worker app is complete...'
        }
    }
}
